### ISSUE TITLE
Split itemize.js and Object.assign polyfill

### ISSUE THREAD

**Issue by GrosSacASac** [Kosmoon/itemizejs#2]
Or even better remove Object.assign polyfill entirely and document the fact that it is a requirement when using the library.

**Comment by Kosmoon** [comment]
This polyfill is fairly small. Don't you think that It would be a shame to break IE compatibility just for that?

**Comment by GrosSacASac** [comment]
IE compatibility would be like this
```
<script nomodule src="https://cdn.jsdelivr.net/npm/itemizejs/Object.assign.js"></script>
<script src="https://cdn.jsdelivr.net/npm/itemizejs/itemize.js"></script>
```
this would remove bloat for browser that already have the support.

Also people who target IE usually have 1 big polyfill file (via @babel/polyfill or core-js) that already does it. If it is not split they will have the same code twice.

**Comment by Kosmoon** [comment]
I want a lambda user to only use one script tag for this library. Even if i think that for @babel/polyfill users, the recursiveness is insignificant, i will investigate on a workaround. Thank you.
