### ISSUE TITLE
src/ actually does not contain the source

### ISSUE THREAD

**Issue by GrosSacASac** [Kosmoon/itemizejs#3]
Your source is _itemize.js_. It can be confusing that you put output files into a src/ directory.
I recommend build, built, dist, distribution, artefacts, or similar names for output files

**Comment by Kosmoon** [comment]
Thank you for letting me know.

**Comment by GrosSacASac** [comment]
don't forget to change package.json to point to the new path e.g.

  "main": "itemize.js",
->
  "main": "src/itemize.js",
